version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo "Copying Lambda code to S3..."
      - aws s3 cp ./lambda/ s3://$S3_BUCKET/$S3_CODE_PREFIX/ --recursive
artifacts:
  files:
    - appspec.yml